# This file was generated by GoReleaser. DO NOT EDIT.
class Gw < Formula
  desc "A CLI used to deploy assets to a Tyler Technologies Kong API Gateway deployment"
  homepage "https://github.com/tyler-technologies/api-gateway-cli"
  version "0.0.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tyler-technologies/api-gateway-cli/releases/download/0.0.10/gw_0.0.10_macos_x64.tar.gz"
    sha256 "f1acf44f77db8510ac86e4b1210d4a04260195f09fb2831892c2e48c926d7ed6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tyler-technologies/api-gateway-cli/releases/download/0.0.10/gw_0.0.10_linux_x64.tar.gz"
      sha256 "bac23bdff3c6236651efdb66155d35cc9a521cd6c1a45124b80010837050fc78"
    end
  end

  def install
    bin.install "gw"
  end

  test do
    system "#{bin}/gw --version"
  end
end
