# This file was generated by GoReleaser. DO NOT EDIT.
class Gw < Formula
  desc "A CLI used to deploy assets to a Tyler Technologies Kong API Gateway deployment"
  homepage "https://github.com/tyler-technologies/api-gateway-cli"
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tyler-technologies/api-gateway-cli/releases/download/v0.0.8/gw_0.0.8_macos_x64.tar.gz"
    sha256 "659385608ce0448c6e8660dcc31eca78c251d21c22896c04681a2bdf7503afa9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tyler-technologies/api-gateway-cli/releases/download/v0.0.8/gw_0.0.8_linux_x64.tar.gz"
      sha256 "482b5e9f48d835a5be3a6e5f54aec139f57685ed51b8dd2706723ee1911846cf"
    end
  end

  def install
    bin.install "gw"
  end

  test do
    system "#{bin}/gw --version"
  end
end
